if(TARGET_PROCESSOR STREQUAL "riscv32")
    include(${CMAKE_CURRENT_LIST_DIR}/toolchain_riscv.cmake)
elseif( TARGET_PROCESSOR STREQUAL "m0"  OR TARGET_PROCESSOR STREQUAL "m0plus" 
    OR TARGET_PROCESSOR STREQUAL "m3"   OR TARGET_PROCESSOR STREQUAL "m33"
    OR TARGET_PROCESSOR STREQUAL "m4"   OR TARGET_PROCESSOR STREQUAL "m4f" OR TARGET_PROCESSOR STREQUAL "m7")
    include(${CMAKE_CURRENT_LIST_DIR}/toolchain-arm.cmake)
else()
   message(FATAL_ERROR "you need set TARGET_PROCESSOR =>" "m0 m0plus m3 m33 m4 m4f m7 riscv32")
endif() 
